### ISSUE TITLE
Default config is not valid!

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#162]
It causes SockBot to crash:

```
[17:15:27] Starting SockBot 2.0.0 Smeghead
Server started! You can access it at localhost:8000
[17:15:27] SockBot `undefined` Started
[17:15:27] Polling Messages
/home/ubuntu/workspace/SockMon/node_modules/sockbot/notifications.js:57
    internals.events.onChannel('/notification/' + config.user.id, privateFns.o
                    ^
TypeError: Cannot read property 'onChannel' of undefined
    at Object.start (/home/ubuntu/workspace/SockMon/node_modules/sockbot/notifications.js:57:21)
    at /home/ubuntu/workspace/SockMon/node_modules/sockbot/SockBot.js:93:27
    at Object.queue.push.callback (/home/ubuntu/workspace/SockMon/node_modules/sockbot/browser.js:508:17)
    at null._onTimeout (/home/ubuntu/workspace/SockMon/node_modules/sockbot/browser.js:168:35)
    at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by AccaliaDeElementia** [comment]
resolved by d059e54

Discourse was returning a 200 series empty string on login with bad credentials rather than a 403 as expected. Updated to catch this case and prevent continuing in this case.
